CREATE TABLE "PayloadPortfolio_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "PayloadPortfolio_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "PayloadPortfolio_media" (
	"id" serial PRIMARY KEY NOT NULL,
	"filename" text NOT NULL,
	"alt" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "PayloadPortfolio_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PayloadPortfolio_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "PayloadPortfolio_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PayloadPortfolio_users" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"name" varchar(255),
	"password" varchar(255),
	"reset_password_token" varchar(255),
	"reset_password_expiration" timestamp,
	"login_attempts" integer DEFAULT 0,
	"lock_until" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "PayloadPortfolio_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "PayloadPortfolio_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "PayloadPortfolio_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "PayloadPortfolio_account" ADD CONSTRAINT "PayloadPortfolio_account_user_id_PayloadPortfolio_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."PayloadPortfolio_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PayloadPortfolio_post" ADD CONSTRAINT "PayloadPortfolio_post_created_by_PayloadPortfolio_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."PayloadPortfolio_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PayloadPortfolio_session" ADD CONSTRAINT "PayloadPortfolio_session_user_id_PayloadPortfolio_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."PayloadPortfolio_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "PayloadPortfolio_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "PayloadPortfolio_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "name_idx" ON "PayloadPortfolio_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "PayloadPortfolio_session" USING btree ("user_id");