import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Providers } from "./providers";
import { Navbar } from "~/components/Navbar";
import { AnimatePresence } from "framer-motion";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as SonnerToaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <body className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Providers>
          <div className="flex min-h-screen flex-col">
            <Navbar />
            <AnimatePresence mode="wait">{children}</AnimatePresence>
          </div>
          <Toaster />
          <SonnerToaster />
        </Providers>
      </body>
    </html>
  );
}
